name: Python-CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff pytest

      - name: Lint with Ruff
        run: |
          ruff ./mirtorch

      - name: Test with pytest
        run: |
          pytest ./tests

      - name: Automated Version Bump
        if: github.ref == 'refs/heads/master'
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: "v" # or an empty string if you don't want a prefix
          filename: "pyproject.toml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: github.ref == 'refs/heads/master'
        run: git push && git push --tags
