name: Python-CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - master
      - develop
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pytest

    - name: Lint with Ruff
      run: |
        ruff ./mirtorch
